use_frameworks!

platform :ios, '10.0'

target 'TREmojiRate_Example' do
  pod 'TREmojiRate', :path => '../'

  target 'TREmojiRate_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
